//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practicMVVM.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class rental
    {
        public int IdRental { get; set; }
        public string IdPavilions { get; set; }
        public System.DateTime beginLease { get; set; }
        public System.DateTime endLease { get; set; }
        public int IdTenats { get; set; }
        public int IdEmployee { get; set; }
        public string IdSM { get; set; }
        public int IdRentalStatus { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual pavilions pavilions { get; set; }
        public virtual statusRental statusRental { get; set; }
        public virtual tenats tenats { get; set; }
    }
}
