//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practicMVVM.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Готовая_аренда
    {
        public int ID_Аренды { get; set; }
        public string C__Павильона { get; set; }
        public System.DateTime Начало_Аренды { get; set; }
        public System.DateTime Окончание_Аренды { get; set; }
        public int ID_Арендатора { get; set; }
        public int ID_Сотрудник { get; set; }
        public string ID_ТЦ { get; set; }
        public int Статус_ТЦ { get; set; }
    }
}
