//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practicMVVM.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Готовые_павильоны
    {
        public string C__Павильона { get; set; }
        public string ID_Павильона { get; set; }
        public Nullable<int> Этаж { get; set; }
        public double Площадь { get; set; }
        public decimal Стоимость_за_кв_м { get; set; }
        public double Кооф__Добавочной_стоимости { get; set; }
        public int Статус_Павильона { get; set; }
    }
}
